tinyMCE.addI18n('ca.table_dlg',{
general_tab:"General",
advanced_tab:"Avançat",
general_props:"Propietats generals",
advanced_props:"Propietats avançades",
rowtype:"Tipus de fila",
title:"Inserta/Modifica la taula",
width:"Amplada",
height:"Alçada",
cols:"Columnes",
rows:"Files",
cellspacing:"Espaiat de cel·la",
cellpadding:"Separació de cel·la",
border:"Contorn",
align:"Alineació",
align_default:"Predeterminat",
align_left:"Esquerra",
align_right:"Dreta",
align_middle:"Centrat",
row_title:"Propietats de la fila",
cell_title:"Propietats de la cel·la",
cell_type:"Tipus de cel·la",
valign:"Alineació vertical",
align_top:"Amunt",
align_bottom:"Avall",
bordercolor:"Color del contorn",
bgcolor:"Color del fons",
merge_cells_title:"Vincula les cel·les",
id:"Id",
style:"Estil",
langdir:"Direcció del llenguatge",
langcode:"Codificació del llenguatge",
mime:"Tipus MIME",
ltr:"D'esquerra a dreta",
rtl:"De dreta a esquerra",
bgimage:"Imatge de fons",
summary:"Resum",
td:"Dades",
th:"Capçalera",
cell_cell:"Actualitza la cel·la actual",
cell_row:"Actualitza totes les cel·les en la fila",
cell_all:"Actualitza totes les cel·les en la taula",
row_row:"Actualiza la fila actual",
row_odd:"Actualiza les files senars",
row_even:"Actualiza les files parells",
row_all:"Actualiza totes les files",
thead:"Capçalera de la taula",
tbody:"Cos de la taula",
tfoot:"Peu de la taula",
scope:"Abast",
rowgroup:"Grup de files",
colgroup:"Grup de columnes",
col_limit:"Heu superat el nombre màxim de columnes: {$cols}.",
row_limit:"Heu superat el nombre màxim de files: {$rows}.",
cell_limit:"Heu superat el nombre màxim de cel·les: {$cells}.",
missing_scope:"Esteu segur que voleu continuar sense especificar l'abast de la capçalera de la cel·la? Sense ella podria dificultar a alguns usuaris entendre el contingut o les dades mostrades de la taula.",
caption:"Subtítol de la taula",
frame:"Marc",
frame_none:"cap",
frame_groups:"grups",
frame_rows:"files",
frame_cols:"columnes",
frame_all:"tots",
rules:"Regles",
rules_void:"buit",
rules_above:"amunt",
rules_below:"avall",
rules_hsides:"hsides",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"capça",
rules_border:"contorn"
});
